# Importation des Librairies

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import csv

from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.autograd as autograd
import torch.optim as optim

## 1. Préparation des données

1.1 Importer les données Train et Test

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [11]:
train_path = '/content/drive/MyDrive/Data_Science/train_clean.csv'
test_path = '/content/drive/My Drive/Data_Science/test_clean.csv'

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

1.2 Depuis le Dataframe train, charger les features d'apprentissage dans un array numpy X_alltrain, et les labels (données à prévoir) dans un array numpy y_alltrain

In [12]:
X_alltrain = train_df.drop(columns=['Survived']).to_numpy()
y_alltrain = train_df['Survived'].to_numpy()

1.3 Séparer les features et les labels en deux parties (train et dev), en attribuant 10% des exemples aux données de dev. afficher les nombres de lignes et de colonnes pour les 4 arrays.

In [14]:
X_train, X_dev, y_train, y_dev = train_test_split(X_alltrain, y_alltrain, test_size=0.1, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_dev shape: {X_dev.shape}")
print(f"y_dev shape: {y_dev.shape}")

X_train shape: (801, 8)
y_train shape: (801,)
X_dev shape: (90, 8)
y_dev shape: (90,)


1.4 Afficher les 10 premières lignes de features et les 10 premiers labels.

In [15]:
print("10 premieres lignes des features:")
print(X_train[:10])
print("10 premiers labels:")
print(y_train[:10])

10 premieres lignes des features:
[[166   3   1   0   2   0   0   4]
 [542   3   0   0   3   0   0   2]
 [626   1   1   3   3   0   1   1]
 [389   3   1   2   0   2   1   1]
 [ 77   3   1   0   0   0   1   1]
 [282   3   1   1   0   0   1   1]
 [713   1   1   2   3   0   0   1]
 [339   3   1   2   1   0   1   1]
 [328   2   0   2   1   0   1   3]
 [322   3   1   1   0   0   1   1]]
10 premiers labels:
[1 0 0 0 0 0 1 1 1 0]


## 2. Définition du réseau de neurone

2.1 Définir et instancier une classe Titanic Model avec les caractéristiques suivantes :
- deux  couches cachées de 50 neurones.
- deux classes en sortie : Survivant ou non
- Des fonctions d'activation RELU
- un dropout paramétrable pour les 2 couches cachées

In [17]:
class TitanicModel(nn.Module):
    def __init__(self, input_size, dropout_prob):
        super(TitanicModel, self).__init__()
        self.hidden1 = nn.Linear(input_size, 50)
        self.hidden2 = nn.Linear(50, 50)
        self.output = nn.Linear(50, 2)
        self.dropout = nn.Dropout(dropout_prob)

    def forward(self, x):
        x = F.relu(self.hidden1(x))
        x = self.dropout(x)
        x = F.relu(self.hidden2(x))
        x = self.dropout(x)
        x = self.output(x)
        return x

input_size = X_train.shape[1]
dropout_prob = 0.5
model = TitanicModel(input_size, dropout_prob)

2.2 : Définir des paramètres de nombre d'epochs (50) et de learning_rate (0.01)

In [18]:
epochs = 50
learning_rate = 0.01

2.3 définir la taille du minibatch à 50. En déduire le nombre de boucle pour chaque epoch.

In [19]:
batch_size = 50
n_batches = len(X_train) // batch_size
print(f"Nombre de boucles par epoch: {n_batches}")

Nombre de boucles par epoch: 16


2.4 Définir un fonction de coût de type CrossEntropy

In [20]:
criterion = nn.CrossEntropyLoss()

2.5. Définir un optimizer de type Adam, sans oublier le learning rate

In [21]:
optimizer = optim.Adam(model.parameters(), lr=learning_rate)


## 3. Apprentissage

3.1 exécuter l'apprentissage du modèle.
- Créer une boucle sur les epochs, qui contient elel-même une boucle sur les minibatchs.
- A chaque nouvelle itération sur les epochs, mélanger les données avec la méthode shuffle.
- Tous les 5 epochs afficher la valeur de la fonction de cout

In [22]:
for epoch in range(epochs):
    X_train, y_train = shuffle(X_train, y_train)  # Mélanger les données
    for i in range(0, len(X_train), batch_size):
        X_batch = torch.tensor(X_train[i:i+batch_size], dtype=torch.float32)
        y_batch = torch.tensor(y_train[i:i+batch_size], dtype=torch.long)

        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()

    if epoch % 5 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")


Epoch 0, Loss: 1.2397563457489014
Epoch 5, Loss: 0.5006052851676941
Epoch 10, Loss: 0.482183575630188
Epoch 15, Loss: 0.456382691860199
Epoch 20, Loss: 0.9251636862754822
Epoch 25, Loss: 1.013568639755249
Epoch 30, Loss: 0.9732825756072998
Epoch 35, Loss: 1.016305685043335
Epoch 40, Loss: 0.4468396306037903
Epoch 45, Loss: 0.9204972386360168


3.2 Calculer la précision de la prévision sur les données dev

In [23]:
X_dev_tensor = torch.tensor(X_dev, dtype=torch.float32)
y_dev_tensor = torch.tensor(y_dev, dtype=torch.long)

with torch.no_grad():
    outputs = model(X_dev_tensor)
    predictions = torch.argmax(outputs, dim=1)
    accuracy = (predictions == y_dev_tensor).float().mean()
    print(f"Dev Accuracy: {accuracy.item() * 100:.2f}%")


Dev Accuracy: 60.00%


3.3 Calculer prévisions sur les données de tests

In [24]:
X_test_tensor = torch.tensor(test_df.drop(columns=['PassengerId']).values, dtype=torch.float32)

with torch.no_grad():
    test_outputs = model(X_test_tensor)
    test_predictions = torch.argmax(test_outputs, dim=1)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (418x7 and 8x50)

3.4 Générer le fichier résultat et l'envoyer sur kaggle
Quel est votre score et votre classement ?

In [ ]:
submission = pd.DataFrame({
    'PassengerId': test_df['PassengerId'],
    'Survived': test_predictions.numpy()
})
submission.to_csv('/content/drive/My Drive/submission.csv', index=False)
print("Fichier de soumission généré.")


3.5 (Optionnel) Exécuter une Cross Validationd ans une boucle pour trouver les meilleures valeurs de learning rate, de keep_prob et de nombre d'epochs.

Cross_Validation avec skkearn : https://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators